# Generated by Django 5.2.7 on 2025-10-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('spots_left', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Test Date',
                'verbose_name_plural': 'Test Dates',
                'ordering': ['date'],
            },
        ),
    ]
