# Generated by Django 5.2.7 on 2025-10-27 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdate',
            options={},
        ),
        migrations.RemoveField(
            model_name='testdate',
            name='spots_left',
        ),
        migrations.AddField(
            model_name='testdate',
            name='max_spots',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.testdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'test_date')},
            },
        ),
    ]
