# Generated by Django 5.2.7 on 2025-10-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_testdate_options_remove_testdate_spots_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdate',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
