# Generated by Django 5.2.7 on 2025-10-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testdate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdate',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
